version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      args:
        JAR_FILE: build/libs/*.jar
    environment:
      - MARVEL_API_HASH=${MARVEL_API_HASH}
      - MARVEL_API_PUBLIC_KEY=${MARVEL_API_PUBLIC_KEY}
    ports:
      - 8080:8080